fieldLayouts:
  cb828eb1-52b0-4916-a1a1-780e1facce99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f9905a0d-83e0-4f77-9abd-13e503ad6526
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25dfa9d0-eb98-417d-b95b-868d85110433
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
