columnSuffix: ysaslqff
contentColumnType: text
fieldGroup: 8441a73d-9a66-4bd0-b906-930da967b794 # Blog
handle: summary
instructions: 'Summaries should be one or two sentences.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
